import { FormEvent, useEffect, useState } from "react";
import { Building2, Plus, Search } from "lucide-react";
import { toast } from "sonner";
import SidebarRail from "@/components/SidebarRail";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Supplier, SupplierCreateData, SupplierType, supplierApi } from "@/lib/api";

const types: SupplierType[] = ["DMC", "Hotel", "Flight supplier", "Online portal", "Tour operator", "Transfer company", "Local supplier", "Other"];
const initial: SupplierCreateData = { name: "", type: "DMC", status: "Active", country: "", email: "", phone: "", whatsapp: "", website: "", currency: "USD", paymentTerms: "", contacts: [], notes: "" };

export default function SuppliersWorkspace() {
  const [suppliers, setSuppliers] = useState<Supplier[]>([]); const [search, setSearch] = useState(""); const [showForm, setShowForm] = useState(false); const [form, setForm] = useState(initial); const [saving, setSaving] = useState(false);
  const load = (q = "") => supplierApi.list(q).then(setSuppliers).catch(() => toast.error("Could not load suppliers"));
  useEffect(() => { void load(); }, []);
  const submit = async (event: FormEvent) => { event.preventDefault(); setSaving(true); try { const supplier = await supplierApi.create(form); setSuppliers((current) => [...current, supplier].sort((a, b) => a.name.localeCompare(b.name))); setForm(initial); setShowForm(false); toast.success("Supplier created"); } catch (error) { toast.error(error instanceof Error ? error.message : "Could not create supplier"); } finally { setSaving(false); } };
  return <div className="min-h-screen bg-[#F5F7FB] flex"><SidebarRail /><main className="min-w-0 flex-1 p-6"><div className="mx-auto max-w-6xl"><div className="mb-6 flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-medium text-[#2063E9]">Travel network</p><h1 className="mt-1 text-3xl font-semibold tracking-tight text-slate-900">Suppliers</h1><p className="mt-2 text-sm text-slate-500">Manage the hotels, DMCs, airline portals, and local partners you source from.</p></div><Button onClick={() => setShowForm((open) => !open)}><Plus className="mr-1.5 h-4 w-4" />New supplier</Button></div>
    {showForm && <form onSubmit={submit} className="mb-6 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="text-base font-semibold text-slate-900">Supplier profile</h2><div className="mt-4 grid grid-cols-1 gap-4 md:grid-cols-2"><label className="text-sm font-medium text-slate-700">Supplier name<Input required value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} className="mt-1.5 h-10" /></label><label className="text-sm font-medium text-slate-700">Supplier type<select value={form.type} onChange={(e) => setForm({ ...form, type: e.target.value as SupplierType })} className="mt-1.5 h-10 w-full rounded-md border border-slate-200 bg-white px-3 text-sm">{types.map((type) => <option key={type}>{type}</option>)}</select></label><label className="text-sm font-medium text-slate-700">Country<Input value={form.country} onChange={(e) => setForm({ ...form, country: e.target.value })} className="mt-1.5 h-10" /></label><label className="text-sm font-medium text-slate-700">Currency<Input maxLength={3} value={form.currency} onChange={(e) => setForm({ ...form, currency: e.target.value.toUpperCase() })} className="mt-1.5 h-10" /></label><label className="text-sm font-medium text-slate-700">Email<Input type="email" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} className="mt-1.5 h-10" /></label><label className="text-sm font-medium text-slate-700">Phone / WhatsApp<Input value={form.phone} onChange={(e) => setForm({ ...form, phone: e.target.value })} className="mt-1.5 h-10" /></label><label className="md:col-span-2 text-sm font-medium text-slate-700">Payment terms<Input value={form.paymentTerms} onChange={(e) => setForm({ ...form, paymentTerms: e.target.value })} placeholder="e.g. Payment 14 days before check-in" className="mt-1.5 h-10" /></label></div><div className="mt-5 flex justify-end gap-2"><Button type="button" variant="outline" onClick={() => setShowForm(false)}>Cancel</Button><Button disabled={saving}>{saving ? "Saving..." : "Create supplier"}</Button></div></form>}
    <div className="mb-4 flex max-w-md items-center gap-2 rounded-xl border border-slate-200 bg-white px-3 shadow-sm"><Search className="h-4 w-4 text-slate-400" /><Input value={search} onChange={(e) => { setSearch(e.target.value); void load(e.target.value); }} placeholder="Search suppliers" className="h-10 border-0 px-0 shadow-none focus-visible:ring-0" /></div>
    <div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{suppliers.map((supplier) => <article key={supplier._id} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-start justify-between gap-3"><div className="flex min-w-0 gap-3"><div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-sky-50 text-sky-700"><Building2 className="h-5 w-5" /></div><div className="min-w-0"><h2 className="truncate font-semibold text-slate-900">{supplier.name}</h2><p className="mt-0.5 text-sm text-slate-500">{supplier.type}{supplier.country ? ` · ${supplier.country}` : ""}</p></div></div><span className={`rounded-full px-2 py-1 text-xs font-medium ${supplier.status === "Preferred" ? "bg-emerald-50 text-emerald-700" : "bg-slate-100 text-slate-600"}`}>{supplier.status}</span></div><div className="mt-5 space-y-1 text-sm text-slate-600"><p>{supplier.email || "No email"}</p><p>{supplier.phone || "No phone"}</p><p className="pt-1 text-xs text-slate-400">Currency: {supplier.currency || "USD"}{supplier.paymentTerms ? ` · ${supplier.paymentTerms}` : ""}</p></div></article>)}{!suppliers.length && <div className="md:col-span-2 xl:col-span-3 rounded-2xl border border-dashed border-slate-300 bg-white p-10 text-center text-sm text-slate-500">No suppliers found. Create your first supplier to start sourcing travel services.</div>}</div>
  </div></main></div>;
}
